language: perl
perl:
  - "5.8.7"
  - "5.8"
  - "5.10.0"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
  - "dev"
matrix:
  include:
    - perl: 5.8.1
      env: AUTHOR_TESTING=0
    - perl: 5.8
      env: COVERAGE=codecov
    - perl: 5.26
      env: COVERAGE=codecov
  allow_failures:
    - perl: 5.6.2
      env: AUTHOR_TESTING=0
sudo: false
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
branches:
  except:
    - /^wip\//
    - /^blocked/
notifications:
  email: false
  irc:
    channels:
      - "irc.perl.org#moo-smoke"
    template:
      - "%{repository}#%{build_number} %{branch} by %{author}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
    skip_join: true
